### ISSUE TITLE
`click.trigger` is associated with the custom element, not the thing inside it

### ISSUE THREAD

**Issue by egeland** [Thanood/aurelia-mdl-skeleton-navigation#19]
If you add a `click.trigger` to a button, `<mdl-button click.trigger="someMethod()">`, and then set the button to disabled `<mdl-button click.trigger="someMethod()" disabled.bind="true">`, the click is still triggered even though the button LOOKS disabled.

Obviously, this is because the click happens on the `mdl-button` element, not on the `button` element inside it..

I think we need to push the trigger through to the button somehow, but I've not been successful in doing it.

**Comment by egeland** [comment]
From looking at https://github.com/adarshpastakia/aurelia-ui-framework/blob/release/components/ui-input.html the way to pass it through is non-trivial..

**Comment by Thanood** [comment]
Hmm, I guess that is the reason why aurelia-kendoui-plugin uses custom attributes on existing DOM (or "form") elements instead of wrapping them in custom elements.

It could probably be done by intercepting the button-click in the component and stop propagation, then firing a custom event or refiring the native DOM event. But I think that smells..

Click would be just the beginning.. Mouseover/mouseout will probably also be fired on the native button for example. And then input events: onchange, onkeyup, textinput, blur, focus.. :-)

Will have to think about it. Maybe a custom attribute is the cleaner solution.

**Comment by Thanood** [comment]
Very interesting.. If you use `click.delegate="someMethod()"` the event is triggered on the inner button (at least if there is also a delegate). Also it seems like `.trigger()` is fired before anything else so it's not "interceptable" - it happens before the element can do anything about it.

Looking more closely at aurelia-ui-framework now and how they do it.

**Comment by Thanood** [comment]
In the end this was pretty easy. :)

Turns out if you don't disable the inner button you can attach an own trigger handler which cancels bubbling. Luckily MDL has also a "disabled" style which is now applied in `disabled = true`. That part needs some polish though.

**Comment by egeland** [comment]
Oh, great stuff! :grinning: 

I'll read through your changes, learn a few things! Maybe upgrade myself from "total n00b" to "kinda n00b-ish".. :laughing:

**Comment by Thanood** [comment]
Oh well, I'm not an expert either. :smile:
